apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
#apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: albert-training
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: inkmanapp
  template:
    metadata:
      labels:
        app: inkmanapp
    spec:
      containers:
      - name: albertrest
        image: albertoclarit/rest:1.0.1 #auto lastest
        ports:
        - containerPort: 4567