apiVersion: v1
kind: Service
metadata:
  name: albert-training-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 4567
    protocol: TCP
  selector:
    app: inkmanapp